# ASCII-only. PowerShell 7+
# Make or update an archive entry for a roadmap step under docs/archives.
# Usage examples:
#   pwsh -File tools/archive/make_step_archive.ps1 --Step 04
#   pwsh -File tools/archive/make_step_archive.ps1 --Step 04 --OutDir docs/archives

param(
    [Parameter(Mandatory=$true)]
    [string]$Step,
    [string]$OutDir = "docs/archives",
    [string]$RoadmapDir = "docs/roadmap",
    [string]$IndexPath = "docs/archives/README.md"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3

function Read-EnvOrEmpty([string]$name) {
    $value = [Environment]::GetEnvironmentVariable($name)
    if ($value) { return [string]$value }
    return ""
}

$refPath = Join-Path $RoadmapDir ("step-" + $Step + ".md")
$refLine = "Ref: $refPath"

# Collect context
$sha = if ($env:GITHUB_SHA) { $env:GITHUB_SHA } else { (git rev-parse HEAD) }
$prNum = ""
$prBody = Read-EnvOrEmpty "PR_BODY"

if (-not $prBody -and $env:GITHUB_EVENT_PATH -and (Test-Path -LiteralPath $env:GITHUB_EVENT_PATH)) {
    try {
        $evt = Get-Content -LiteralPath $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
        if ($evt.pull_request -and $evt.pull_request.body) { $prBody = [string]$evt.pull_request.body }
        if ($evt.pull_request -and $evt.pull_request.number) { $prNum = [string]$evt.pull_request.number }
    } catch { }
}

if ((-not $prNum) -and (Get-Command gh -ErrorAction SilentlyContinue)) {
    try { $prNum = (gh pr view --json number 2>$null | ConvertFrom-Json).number } catch { }
}

$now = [DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss 'UTC'")

# Ensure output dir
if (-not (Test-Path -LiteralPath $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }

# Build per-step file content
$stepFile = Join-Path $OutDir ("step-" + $Step + ".md")
$summary = if ($prBody) { $prBody.Trim() } else { "(no PR body available)" }

$stepMd = @()
$stepMd += "# Step-" + $Step + " Archive"
$stepMd += ""
$stepMd += $refLine
$stepMd += ""
$stepMd += "- Date: " + $now
$stepMd += "- Commit: " + $sha
$stepMd += if ($prNum) { "- PR: #" + $prNum } else { "- PR: (n/a)" }
$stepMd += ""
$stepMd += "## Summary"
$stepMd += $summary
$stepMd += ""
$stepMd += "## Notes"
$stepMd += "- Generated by tools/archive/make_step_archive.ps1"

Set-Content -LiteralPath $stepFile -Value ($stepMd -join "`n") -Encoding UTF8
Write-Host ("Wrote " + $stepFile)

# Update index table
if (-not (Test-Path -LiteralPath $IndexPath)) {
    $idx = @()
    $idx += "# Archives Index"
    $idx += ""
    $idx += "This folder stores step snapshots (one file per roadmap step) and an index."
    $idx += ""
    $idx += "| Step | Date (UTC) | PR | Commit | Ref |"
    $idx += "|------|------------|----|--------|-----|"
    Set-Content -LiteralPath $IndexPath -Value ($idx -join "`n") -Encoding UTF8
}

$line = "| step-" + $Step + " | " + $now + " | " + $(if ($prNum) { "#" + $prNum } else { "(n/a)" }) + " | " + $sha.Substring(0,7) + " | " + $refPath + " |"

# Append only if not present
$idxContent = Get-Content -LiteralPath $IndexPath -Raw
if ($idxContent -notmatch ([regex]::Escape("| step-" + $Step + " |"))) {
    Add-Content -LiteralPath $IndexPath -Value $line
    Write-Host "Index updated"
} else {
    Write-Host "Index already contains this step"
}
